include config.mk

Line_Prefix := ....
Nothing :=

define GDBInit_Template

....#Auto generated by Makefile. Do not modify.
....
....target remote $(GDB_Server_Host):$(GDB_Server_Port)
....
....monitor device $(Target_Device)
....monitor si 1
....monitor speed $(Debugger_Speed)
....
....file $(Elf_File)
....
....define run
....    load
....    monitor reset
....end
....
....define r
....    continue
....end
....
....define flash
....    shell $(Debugger_Flash_Command)
....end

endef

Script := $(subst $(Line_Prefix),$(Nothing), $(GDBInit_Template))

define Debugger_Service_Template

....#Auto generated by Makefile. Do not modify.
....
....[Unit]
....Description=$(Debugger_Service_Description)
....After=default.target
....
....[Service]
....ExecStart=$(Debugger_GDB_Server_Command)
....Type=simple
....
....[Install]
....WantedBy=default.target

endef

Unit_File := $(subst $(Line_Prefix),$(Nothing), $(Debugger_Service_Template))

register_safe_path := add-auto-load-safe-path $(PWD)/$(Local_GDBInit_File)

.PHONY: all clean

all: $(Local_GDBInit_File) $(Debugger_Service_Installed)

$(Local_GDBInit_File): config.mk gdb-server.mk
	$(info $@)
	$(info $(Script))
	$(file >$@, $(Script))
	$(file >>$(User_GDBInit_File),$(register_safe_path))
	echo "Created $(@)"

$(Debugger_Service_Unit_File): config.mk gdb-server.mk
	$(info $(Unit_File))
	$(file >$@, $(Unit_File))
	echo "Created $(@)"

$(Debugger_Service_Install_Location):
	mkdir -p $@

$(Debugger_Service_Installed): $(Service_Install_Path) $(Debugger_Service_Unit_File)
	cp $(Debugger_Service_Unit_File) $(Service_Install_Path)
	systemctl --user daemon-reload

Start_Debug_Service: $(Debugger_Service_Installed)
	systemctl --user start $(Debugger_Service_Unit_File)

Stop_Debug_Service: $(Debugger_Service_Installed)
	systemctl --user stop $(Debugger_Service_Unit_File)

clean:
	rm $(Local_GDBInit_File)
	rm $(Debugger_Service_Installed)
	rm $(Debugger_Service_Unit_File)
