include config.mk

include gdb-server.mk

OBJCOPY := arm-none-eabi-objcopy

.PHONY: all build_dir flash debug_init jlink_stop jlink jlink_flash

all: debug


$(DEBUG_FLASH_CMD):
	@echo -e "#Auto generated by Makefile. Do not modify." > $@
	@echo -e "#If you must, modify $(JLINK_FLASH_CMD) recipe in Makefile" >> $@
	@echo -e "exitonerror 1" >> $@
	@echo -e "device $(DEBUG_DEVICE)" >> $@
	@echo -e "si $(DEBUG_INTERFACE)" >> $@
	@echo -e "speed auto" >> $@
	@echo -e "h" >> $@
	@echo -e "r" >> $@
	@echo -e "erase" >> $@
	@echo -e "loadbin $(BUILD_TARGET_BIN) $(FLASH_BASE_ADDRESS)" >> $@
	@echo -e "verifybin $(BUILD_TARGET_BIN) $(FLASH_BASE_ADDRESS)" >> $@
	@echo -e "exit" >> $@

jlink_flash: $(DEBUG_FLASH_CMD)
	JLinkExe -commanderscript $< 

debug: $(Debugger_Service_Installed) $(Local_GDBInit_File) Start_Debug_Service
	gdb

stop_debug: Stop_Debug_Service
	
clean:
	$(RM) $(BUILD_DIR)
	$(RM) $(DEBUG_FLASH_CMD) 
	$(RM) $(DEBUG_CONFIG)
